export const SINCRO_OBRA_SOURCE = "Sincro Obra";

export type SincroObraSeed = {
  businessName: string;
  email: string;
  phone: string;
  segment: string;
  owner: "Franco";
  status: string;
  notes: string;
};

const rows = [
  ["Arq. Facu Cataldo","","5491158183589","Facu / WhatsApp directo","Pendiente","Canal recomendado: WhatsApp personal"],
  ["Arquitecto Nicolás Castagnino","","5491131301868","Facu / WhatsApp directo","Pendiente","Canal recomendado: WhatsApp personal"],
  ["Arq. Nayla Passantino","","5491160482966","Facu / WhatsApp directo","Pendiente","Canal recomendado: WhatsApp personal"],
  ["Arq. Axel del Viso","","5492916416667","Facu / WhatsApp directo","Pendiente","Canal recomendado: WhatsApp personal"],
  ["Gimenez Arquitectos","","5491159703861","Facu / WhatsApp directo","Pendiente","Contacto: Arq Hernan Gimenez · Canal recomendado: WhatsApp personal"],
  ["Checa Arquitectos","cvchecaarquitectos@gmail.com","","Estudio","Contactado","Canal recomendado: Email"],
  ["Estudio LivingSton","clientes@estudiolivingston.com.ar","5401175440939","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["MDBK","info@mdbk.com.ar","5491127795722","Estudio","Propuesta enviada","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["pEREYRA iRAOLA","info@rpiarq.com.ar","541124925024","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["Arq.grupo32","","5491157437796","Estudio","Propuesta enviada","Canal recomendado: WhatsApp"],
  ["rioja-arquitectura","gracerioja@hotmail.com","5491164690508","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["Estudio Plats","info@estudioplats.com.ar","5491161026399","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["RDR Arquitectos","arquitectos@rdra.com.ar","541145485038","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["mazzinghisanchez","","541164635892","Estudio","Contactado","Canal recomendado: WhatsApp"],
  ["apaarquitectura","","5491156019740","Estudio","Contactado","Canal recomendado: WhatsApp"],
  ["hermannarquitectos","hermannarquitectos@gmail.com","5491130673636","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["UFV72","ufv72.nahuelayora@gmail.com","541138386254","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["BASA","","5491173856673","Estudio","Propuesta enviada","Canal recomendado: WhatsApp"],
  ["FCL","info@fclarquitectura.com.ar","5491170658893","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["Cuarto Estudio","cuarto.arq@gmail.com","","Estudio","Contactado","Canal recomendado: Email"],
  ["GUTMAN LEHRER","estudio@gl-arquitectura.com.ar","541145170512","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["dsarquitectos","","541163070760","Estudio","Contactado","Canal recomendado: WhatsApp · Teléfono alternativo: 11 6307 0760"],
  ["lopez wolder","info@lopezwolder.com","","Estudio","Contactado","Canal recomendado: Email"],
  ["IDEI","info@idei.com.ar","","Estudio","Contactado","Canal recomendado: Email"],
  ["santiago cordeyro","info@santiagocordeyro.com.ar","541147934472","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["arcury y ricci","info@amasr.com.ar","5491127681959","Estudio","Propuesta enviada","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["ESTUDIO TEZ","tez.estudio@gmail.com","5491161082468","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["BARBALACO Arquitectos","info@barbalacoarquitectos.com","5491167597586","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["Estudio BDM","info@bdmestudio.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["Bárbara Zoberman Arquitectura","arq.bzoberman@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["xfbarquitectos","","541148888888","Estudio","Contactado","Canal recomendado: WhatsApp"],
  ["barrionuevo arquitectas","arquitectas@barrionuevoarquitectas.com","5491149868497","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["estudioplasma","info@estudioplasma.com","","Estudio","Contactado","Canal recomendado: Email"],
  ["Diaconoarquitectos","diaconoarquitectos@gmail.com","541149174509","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo · Teléfono alternativo: 1149174509"],
  ["idero","rrhh@idero.com.ar","","Estudio","Contactado","Canal recomendado: Email"],
  ["liveinconcept","info@liveinconcept.com","5491148311821","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["DADO","info@dado.com.ar","541147876892","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["SyA","sya.arqs@gmail.com","","Estudio","Contactado","Canal recomendado: Email"],
  ["BARRIONUEVO VILLANUEVA","barrionuevo.n.g@hotmail.com","","Estudio","Contactado","Canal recomendado: Email"],
  ["Estudio Verde Concreto","leila.wainstein@gmail.com","","Estudio","Contactado","Canal recomendado: Email"],
  ["Michelo Guzzo","micheloguzzo@yahoo.com.ar","","Estudio","Contactado","Canal recomendado: Email"],
  ["Lum Arquitectas","lumarquitectas@gmail.com","","Estudio","Contactado","Canal recomendado: Email"],
  ["smrarquitectura","info@smrarquitectura.com.ar","5491153836814","Estudio","Contactado","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["DUM ESTUDIO","dumestudio@gmail.com","","Estudio","Contactado","Canal recomendado: Email"],
  ["sedearq","estudio@sedearq.com","5491150274251","Estudio","Propuesta enviada","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["dxarq","info@dxarq.com.ar","","Estudio","Contactado","Canal recomendado: Email"],
  ["Primal Estudio","info@estudioprimal.com.ar","","Estudio","Contactado","Canal recomendado: Email"],
  ["ASIA ARQ","a.armentano@asia-arq.com","5491149487778","Estudio","Propuesta enviada","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["vivianamelamed","vivianamelamed@gmail.com","541143266414","Estudio","Pendiente","Contacto: 54 11 43260661 · Canal recomendado: WhatsApp primero + Email respaldo"],
  ["mariana flombaum arq","mariana@flombaum.com.ar","541148317807","Estudio","Pendiente","Contacto: 54911 44467868 · Canal recomendado: WhatsApp primero + Email respaldo"],
  ["caceres estudio","obras@arquitectocaceres.com.ar","","Estudio","Pendiente","Canal recomendado: Email"],
  ["Centro Cero Estudio","estudiocentrocero@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["CROMO","sofiatagle.arq@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["familyhouseS","casas@familyhouses.com.ar","541147353406","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["estudioetiqueta","arquitectura@estudioetiqueta.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["latitudsurarq","estudio@latitudsurarq.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["OON ARCHITECTURE","hola@oonarchitecture.com","5491151822453","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["FOCO","contacto@estudiofoco.com","5491122536656","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["radovic_arquitecto","gradovich@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["ESCALANTE VELA","escamarcos@gmail.com","5411479561","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["Estudio Fleggs","info@escalantevela.com.ar","541123878214","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["G2 ESTUDIO","g2arquitectura.mail@gmail.com","5491132073552","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["CD ARQ","arq.cdalessandro@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["monoestudio","info@monoestudio.com.ar","","Estudio","Pendiente","Canal recomendado: Email"],
  ["Av Estudio","arq.papini@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["Ayelen Alcorta Arq","arq.aalcorta@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["T+T Arquitectos","lucianotiscornia@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["la nave arq","lanavearq@gmail.com","541167984671","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["Biaus Pieres Arquitectura","magdalena.biaus@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["Estudio Arquitecta Moriello","contacto@arquitectamoriello.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["gabellinirey","info@gabellinirey.com.ar","541153447019","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["mvictoria.menendez","mvictoria.menendez@hotmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["puntolimite arqs","puntolimite11@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["renderplace","nnrenderplace@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["info@estudiolosa.com","info@estudiolosa.com","5491131543412","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["DIPA ARQS","info@dipaarquitectos.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["DU","info@grupodu.com.ar","","Estudio","Pendiente","Canal recomendado: Email"],
  ["dikka arq","dikkaarquitectura@gmail.com","541135986374","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["kuperdesign construcciones","info@kuperdesignconstrucciones.com","5491165166003","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["VARA ESTUDIO","hola@estudiovara.com.ar","","Estudio","Pendiente","Canal recomendado: Email"],
  ["arq karengarber","arq.karengarber@gmail.com","5491156939200","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["Estudio Fernandez Long & asoc.","info@estudiofernandezlongyasoc.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["Fp arq","mariajoseferrarif@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["Revitalizate","contacto@revitalizatearquitectura.com","5491138781173","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["Efg Estudio Filcman Gurfinkiel","marina@efg.com.ar","541161047814","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["ariana werber arquitecta","contacto@arianawerber.com.ar","541149490908","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo · Teléfono alternativo: 011 49490908"],
  ["CIFARELLI arq","alejandro@cifarelli.com.ar","541146357976","Estudio","Pendiente","Contacto: 54 9 11 3134-0009 · Canal recomendado: WhatsApp primero + Email respaldo"],
  ["LOCKERarq","lockerarq@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["AB ARQUITECTURA","dabiaus@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["DE RAIZ ESTUDIO","info@deraizestudio.com","541161624395","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo · Teléfono alternativo: 1161624395"],
  ["PEKA ARQ","peka.arq@gmail.com","549112253998","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["arqveroporta","arqveroporta@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["jorgefelliarqs","jorgefelliarqs@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["silvia.soqueff","silvia.soqueff@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["Estudio ToyosQuesada","info@toyosquesada.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["HS ARQUITECTURA","arq.schweizer@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["Clara Chediack","clara.chediack@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["emilianociaburri","emilianociaburri@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["ceciliagil.arq","ceciliagil.arq@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["Estudio Trama","arq.amymartelli@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["Organica Estudio","organicaarquitectas@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["B3","hola@b3hogar.com","5491125665981","Estudio","Pendiente","Canal recomendado: WhatsApp primero + Email respaldo"],
  ["OADD arquitectos","oaddarqs@gmail.com","","Estudio","Pendiente","Canal recomendado: Email"],
  ["LGP ARQUITECTURA","lgp.arquitecta@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["Estudio CARDINAL","hello.casarq@gmail.com","","Arquitecto independiente / sin web","Pendiente","Canal recomendado: Delegar web / Email · Sin web: Si"],
  ["Estudio 8.66","valerianifernando@gmail.com","","Estudio de arquitectura","Pendiente",""],
  ["Ebeca","mvhirschfeld@ebeca.com.ar","","Estudio de arquitectura","Pendiente",""],
  ["Suministro de obras","cristian.ramirez.manuel@gmail.com","1153759373","Estudio de arquitectura","Pendiente",""],
  ["Estudio +54","estudio54arq@gmail.com","","Estudio de arquitectura","Pendiente",""],
  ["GEN STUDIO COMOTTO - SOMMER","miscoloresdehoy@gmail.com","","Estudio de arquitectura","Pendiente",""],
  ["Marcela Romiti Arquitectura","romitimarce@gmail.com","","Estudio de arquitectura","Pendiente",""],
  ["Martin Gomez","estudio@martingomezarquitectos.com","5491157071778","Estudio de arquitectura","Pendiente",""],
  ["ABAD GADANO","estudio@abadgadano.com","","Estudio de arquitectura","Pendiente",""],
  ["ESTUDIO DIDOT","casadidot@didotweb.com","541148331044","Estudio de arquitectura","Pendiente","Teléfono alternativo: 54911 4426 0527"],
  ["LOB arquitectura","lobarquitectura@gmail.com","","Estudio de arquitectura","Pendiente",""],
  ["Estudio Guimarey","arqmagaliguimarey@gmail.com","","Estudio de arquitectura","Pendiente",""],
  ["SRMD Arquitectura","info@srmdarquitectura.com.ar","","Estudio de arquitectura","Pendiente",""],
] as const;

export const sincroObraSeeds: SincroObraSeed[] = rows.map(
  ([businessName, email, phone, , status]) => ({
    businessName,
    email,
    phone,
    segment: "Estudio de arquitectura",
    owner: "Franco",
    status,
    notes: "",
  }),
);
